; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "CallMyPhone"
#define MyAppVersion "0.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "CallMyPhone.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FA3C2F1B-FB27-4BEC-868C-B031820AA170}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={userappdata}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=C:\Users\k.batmanov\Documents\build-CallMyPhone-Desktop_Qt_5_11_0_MinGW_32bit-Release\installer
OutputBaseFilename=setup_callmyphone
Compression=lzma
SolidCompression=yes
PrivilegesRequired=lowest

[Languages]
;Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\k.batmanov\Documents\build-CallMyPhone-Desktop_Qt_5_11_0_MinGW_32bit-Release\release\out\CallMyPhone.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\k.batmanov\Documents\build-CallMyPhone-Desktop_Qt_5_11_0_MinGW_32bit-Release\release\out\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
;Регистрируем расширение Outlook
Root: HKCU; Subkey: "Software\Microsoft\Office\Outlook\Addins\CallMyPhoneOutlookAddIn"; ValueType: string; ValueName: "Description"; ValueData: "CallMyPhoneOutlookAddIn"
Root: HKCU; Subkey: "Software\Microsoft\Office\Outlook\Addins\CallMyPhoneOutlookAddIn"; ValueType: string; ValueName: "FriendlyName"; ValueData: "CallMyPhoneOutlookAddIn"
Root: HKCU; Subkey: "Software\Microsoft\Office\Outlook\Addins\CallMyPhoneOutlookAddIn"; ValueType: dword;  ValueName: "LoadBehavior"; ValueData: "00000003"
Root: HKCU; Subkey: "Software\Microsoft\Office\Outlook\Addins\CallMyPhoneOutlookAddIn"; ValueType: string; ValueName: "Manifest"; ValueData: "file:///{userappdata}/CallMyPhone/CallMyPhoneOutlookAddIn/CallMyPhoneOutlookAddIn.vsto|vstolocal"

;Регистрируем звонилку для ссылок tel и callto
Root: HKCU; Subkey: "SOFTWARE\Classes\callto"; ValueType: string; ValueName: ""; ValueData: "URL:callto"
Root: HKCU; Subkey: "SOFTWARE\Classes\callto"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""

Root: HKCU; Subkey: "SOFTWARE\Classes\tel"; ValueType: string; ValueName: ""; ValueData: "URL:tel"
Root: HKCU; Subkey: "SOFTWARE\Classes\tel"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""

Root: HKCU; Subkey: "SOFTWARE\Classes\dialer.callto\Shell\Open\Command"; ValueType: string; ValueName: ""; ValueData: "{userappdata}/CallMyPhone/CallMyPhone.exe %1"

Root: HKCU; Subkey: "SOFTWARE\{#MyAppName}\{#MyAppName}\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "{#MyAppName}"
Root: HKCU; Subkey: "SOFTWARE\{#MyAppName}\{#MyAppName}\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "{#MyAppName}"

Root: HKCU; Subkey: "SOFTWARE\{#MyAppName}\{#MyAppName}\Capabilities\URLAssociations"; ValueType: string; ValueName: "callto"; ValueData: "dialer.callto"
Root: HKCU; Subkey: "SOFTWARE\{#MyAppName}\{#MyAppName}\Capabilities\URLAssociations"; ValueType: string; ValueName: "tel"; ValueData: "dialer.callto"

Root: HKCU; Subkey: "SOFTWARE\RegisteredApplications"; ValueType: string; ValueName: "{#MyAppName}"; ValueData: "SOFTWARE\{#MyAppName}\{#MyAppName}\Capabilities"
